server:
  port: 8105
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
#spring:
#  datasource:
#    password: password
#    url: jdbc:mysql://localhost:3306/lc?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #    JDBC : SGDB :// HOST : PORT / DB
    url: jdbc:postgresql://containers-us-west-13.railway.app:5917/railway
    username: postgres
    password: GfK6FE3LPNYuq6LaTpHL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
